import styled from "@emotion/styled"
import type {NextPage} from "next"
import Head from "next/head"
import Link from "next/link"
import {Fragment} from "react"

import routes from "../data/routes.json"

const Page = styled.div`
  height: 100%;
  border: 1px solid #000;
  display: flex;
  align-items: center;
  justify-content: center;
`

const RoutesList = styled.ul`
  border: 1px solid #000;
  display: flex;
  flex-flow: column wrap;
  align-items: center;
  width: 100%;
`

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Recursion with React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <RoutesList>
          {routes.map(({name, path}) => (
            <li key={name}>
              <Link href={path}>
                <a>{name}</a>
              </Link>
            </li>
          ))}
        </RoutesList>
      </Page>
    </Fragment>
  )
}

export default Home
