import styled from "@emotion/styled"
import {bgNuisances, colorsMain} from "@styles/styles"
import type {NextPage} from "next"
import Head from "next/head"
import Link from "next/link"
import {Fragment} from "react"

import routes from "../data/routes.json"

const Page = styled.div`
  min-height: 60vh;
  margin: 1rem auto;
  display: flex;
  align-items: center;
  justify-content: center;
`

const RoutesList = styled.ul`
  background-color: ${bgNuisances.bg500};
  display: flex;
  flex-flow: column wrap;
  align-items: center;
  padding: 1rem;
  border-radius: 4px;
  min-width: 25em;
  li {
    font-size: 2rem;
    text-transform: uppercase;
    transition: 200ms ease-in-out all;
    &:hover {
      transform: rotate(2deg) scale(1.1);
      color: ${colorsMain.primary};
    }
  }
`

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Recursion with React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <RoutesList>
          {routes.map(({name, path}) => (
            <li key={name}>
              <Link href={path}>
                <a>{name}</a>
              </Link>
            </li>
          ))}
        </RoutesList>
      </Page>
    </Fragment>
  )
}

export default Home
